### ISSUE TITLE
issue: recipes can consume buckets

### ISSUE THREAD

**Issue by BadsyEdgecat** [BlakeBr0/MoreBuckets#4] opened 2019-05-21 20:16 UTC
if you shift click craft something with more potential crafted items than the amount of liquid in the bucket (say, 11 XL Food Mod waffles with a diamond bucket thats 10/10 filled with milk), the recipe will consume the bucket as if its an extra use of milk or whatever liquid bucket and the bucket will disappear.

**Comment by BlakeBr0** [comment] 2023-02-05 21:40
I'm going to close this as I am no longer maintaining the 1.12 version. I tested in 1.19 with Creosote from Immersive Engineering and it works as expected. There's always the potential that a mods custom recipe doesn't handle container items properly which could potentially be the cause of issues like this.

Thanks for the report

**Closed as completed by BlakeBr0** 2023-02-05 21:40 UTC
Labels: Bug, 1.12
